fix: remove GPG signing due to openpgp compatibility issues
Remove GPG signing from chart-releaser workflow because the underlying
golang.org/x/crypto/openpgp library is deprecated and doesn't support
modern GPG key formats (S2K hash functions).

This fixes the publish workflow that was failing with:
  Error: openpgp: unsupported feature: hash for S2K function: 0

Related: https://github.com/golang/go/issues/13605